add i blaze, make environment start automatically.

diff --git a/bin/blaze b/bin/blaze
--- a/bin/blaze
+++ b/bin/blaze
@@ -1,13 +1,36 @@
 #!/bin/bash
 
+if [ ! -f WORKSPACE ]; then
+  echo "No WORKSPACE file present, this should be called in the root directory of a bazel project"
+  exit 1
+fi
+
 if [ ! -f .bazel_docker_id ]; then
-    echo ".bazel_docker_id file not found, please run start_env.sh to start the bazel container."
-    exit 1
+  echo ".bazel_docker_id file not found, starting new bazel container."
+  docker run \
+    --rm -d -it \
+    --name bazel-container \
+    --add-host buildfarm-server:192.168.0.14 \
+    --add-host buildfarm-redis:192.168.0.14 \
+    -v /home/geli/.bazel_in_docker:/home/geli/.bazel_in_docker \
+    -v $PWD:$PWD \
+    -v /tmp:/tmp \
+    192.168.0.14:5000/tf-gpu-env \
+    bash > .bazel_docker_id
 fi
 
 if [ -z $( docker ps -f id=$(cat .bazel_docker_id) -q ) ]; then
-    echo ".bazel_docker_id points to a docker container that is terminated, please run start_env.sh to start the bazel container."
-    exit 1
+  echo ".bazel_docker_id points to a docker container that is terminated, starting new bazel container."
+  docker run \
+    --rm -d -it \
+    --name bazel-container \
+    --add-host buildfarm-server:192.168.0.14 \
+    --add-host buildfarm-redis:192.168.0.14 \
+    -v /home/geli/.bazel_in_docker:/home/geli/.bazel_in_docker \
+    -v $PWD:$PWD \
+    -v /tmp:/tmp \
+    192.168.0.14:5000/tf-gpu-env \
+    bash > .bazel_docker_id
 fi
 
 docker exec -w $PWD $( cat .bazel_docker_id ) bazelisk "$@"
